### ISSUE TITLE
Pipeline Webhook is erroring out due to Stack Overflow.

### ISSUE THREAD

**Issue by tejal29** [knative/build-pipeline#103]
## Expected Behavior
The webhook should be able to admit a valid pipeline resource correctly.

## Actual Behavior
Right now,  for a valid pipeline crd
```
kubectl create -f examples/pipelines/kritis_cp.yaml 
Error from server (InternalError): error when creating "examples/pipelines/kritis_cp.yaml": Internal error occurred: failed calling admission webhook "webhook.pipeline.knative.dev": Post https://build-pipeline-webhook.knative-build-pipeline.svc:443/?timeout=30s: unexpected EOF; some request body already written
```
If you see the error logs for the webhook, you will see they error out due to stack overflow.
```
github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1.(*PipelineSpec).SetDefaults(0xc000254c48)
	/usr/local/google/home/tejaldesai/go/src/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go:23 +0x3a fp=0xc0206c0378 sp=0xc0206c0370 pc=0xab820a
github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1.(*PipelineSpec).SetDefaults(0xc000254c48)
	/usr/local/google/home/tejaldesai/go/src/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go:24 +0x2b fp=0xc0206c0408 sp=0xc0206c03f0 pc=0xab81fb
github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1.(*PipelineSpec).SetDefaults(0xc000254c48)
	/usr/local/google/home/tejaldesai/go/src/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go:24 +0x2b fp=0xc0206c0420 sp=0xc0206c0408 pc=0xab81fb
...additional frames elided...
created by net/http.(*http2serverConn).processHeaders
	/usr/lib/google-golang/src/net/http/h2_bundle.go:5611 +0x4d3
```

## Steps to Reproduce the Problem

  1. Apply a valid pipeline config
```
cat << EOF | kubectl apply -f - 
apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
    tasks:
      - name: unit-test-kritis          # 1.  Run unit Tests
        taskRef:
          name: make
        inputSourceBindings:
          - name: kritis-app-github
            key: workspace # bind to the name in the task
            resourceRef:
              name: kritis-resources-git
        params:
          - name: makeTarget
            value: test
EOF

````
  2.  Check logs for the webhook
```
kubectl logs -l app=build-pipeline-webhook
```

## Additional Info
Offending PR : https://github.com/knative/build-pipeline/pull/94/files
