### ISSUE TITLE
TaskRun should have `Results` in `Status`

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#146]
## Expected Behavior
When `TaskRun` executes, it will upload its logs and results to the locations in `PipelineParams`. A user should be able to look at the Status of a `TaskRun` and see exactly where those logs ended up (i.e. the whole path).

This path should be determined by the controller, e.g. a folder in the path named after the TaskRun and/or timestamp, and provided in the `Status` of the `TaskRun`.

## Actual Behavior
The `TaskRun` _Spec_ (not `Status`!) has [Results](https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/taskrun_types.go#L32) which in a previous iteration of our examples were expected to be provided manually:

https://github.com/knative/build-pipeline/blob/dcc2cb189f268c1a9651499c1c1f6ce5f76b1e02/examples/invocations/run-kritis-test.yaml#L24-L36

I deleted this from the example b/c I was thinking that referencing the PipelineParams was enough.

## Additional Info
Note #107 is about actually making this work, this is more about the API.

**Comment by bobcatfish** [comment]
Note after discussing with @shashwathi , we should keep the results in spec as well, so we need both, e.g.
```
spec:
 results: 
     runs: 
       name: 'runsBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/runs' 
     logs: 
       name: 'logBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/logs' 
     tests: 
       name: 'testBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/tests' 
status:
 results: 
     runs: 
       name: 'runsBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/runs/mytaskrun/' 
     logs: 
       name: 'logBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/logs/mytaskrun' 
     tests: 
       name: 'testBucket' 
       type: 'gcs' 
       url: 'gcs://somebucket/results/tests/mytaskrun' 
```

(This task is just about adding the fields to Status, not about implementing the logic)
