### ISSUE TITLE
Tracking pipeline and task execution time

### ISSUE THREAD

**Issue by tanner-bruce** [knative/build-pipeline#163]
## Expected Behavior
As a user/pipeline developer, I would like to be able to track how long my pipeline execution takes over a period of days/months, at the individual Task level and at the Pipeline level.

## Actual Behavior
There is no way to see this

**Comment by bobcatfish** [comment]
@tejal29 had pointed out in slack that we already have this in the Build step states:

```
    stepStates:
    - terminated:
        containerID: docker://4cb2c0b027c8441a22c39f48ce4c3a1d60e6529b10341d08abfa3d5854477d30
        exitCode: 0
        finishedAt: 2018-10-16T23:03:29Z
        reason: Completed
        startedAt: 2018-10-16T23:03:29Z
    - terminated:
        containerID: docker://cdf53948f5871e18cc1ce00f6a385d02446332823e7ec66bbccdce263ddf6459
        exitCode: 0
        finishedAt: 2018-10-16T23:03:31Z
        reason: Completed
        startedAt: 2018-10-16T23:03:30Z
    - terminated:
        containerID: docker://49dfc0d9498d02557a8f35f0e81d9e5517e2b7f537836604c727ccf399bc244a
        exitCode: 0
        finishedAt: 2018-10-16T23:04:06Z
        reason: Completed
        startedAt: 2018-10-16T23:03:31Z
```

(startedAt and terminatedAt)

Is this the same info you're looking for in this issue? (Is this issue about adding those fields to TaskRun + PipelineRun?)
