### ISSUE TITLE
Link `outputSourceBindings` to build

### ISSUE THREAD

**Issue by shashwathi** [knative/build-pipeline#171]
Below is a pipeline with a task which has an input source to `push-kritis` and outputs the image to `kritisImage` resource. Currently there is no mechanism to capture the `kritisImage` metadata. 
We need this information to use specific version of resource in further tasks of the pipeline.
 
```
apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
  tasks:
    - name: push-kritis              
      taskRef:
        name: build-push
      inputSourceBindings:
        - name: kritis-app-github
          key: workspace 
          resourceRef:
            name: kritis-repo-git
      outputSourceBindings:
        - name: kritisImage
          key: builtImage 
          resourceRef:
            name: kritis-resources-image
```

## Expected Behavior
Build or TaskRun should hold resource references to `outputSourceBindings` generated.

## Actual Behavior
`outputSourceBindings` of task is not used.

## Additional Info
This should be completed before tackling: https://github.com/knative/build-pipeline/issues/148
This change might require build to be rendered inside build-pipeline.
