### ISSUE TITLE
Add support for `clusters`

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#177]
## Expected Behavior
It should be possible to deploy to the clusters in PipelineParams:

https://github.com/knative/build-pipeline/blob/fc4775ae44546a68fad8c951073904e5dd51fca3/examples/pipelineparams.yaml#L8-L14

For example, I should be able to make a task like this:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: helm
  namespace: default
spec:
    inputs:
        resources:
            - name: workspace
              type: github
            - name: imageToDeploy
              type: image
        params:
            - name: pathToHelmCharts
              value: string
            - name: helmArgs
              value: string
        cluster:
            - name: clusterToDeployTo
    buildSpec:
        steps:
        - name: deploy
          image: kubernetes-helm
          args: ['deploy', '--path=${pathToHelmChart}', '--set image=${imageToDeploy.Url}.${imageToDeploy.Name}', '${helmArgs}', '--kubeconfig=${clusterToDeployTo.somemagickubeconfigpath}']
```

I _think_ the best way to make this work generically for any deployment tool is to create and mount a kubeconfig automatically (e.g. so we can use helm's `--kubeconfig` arg) but definitely option to other options!

It's crucial this works for more than just helm.

_Bonus: we actually want clusters to be in a resource, so you could also move them out of PipelineParams into a Resource type! Note that in #68 we want to make a Deployment type as well, which would probably also include the helm / kubectl /tool of choice functionality but that's a ways off_

## Actual Behavior
At the moment the clusters in PipelineParams are ignored, so you can only really deploy to the cluster running the Pipeline CRD.

You could also hardcode the info for another cluster into your Task, but that's less than ideal!

## Steps to Reproduce the Problem

  1. Create a PipelineParams that includes a cluster
  2. Create a deploy task that deploys using Helm, and give it a cluster parameter
  3. Note that you have pretty much no way to link the actual helm command in the Task with the Cluster

## Additional Info
In #63 we added an integration test that does a deployment, but it only deploys to the cluster that the Pipeline CRD is running in - we need to udpate the test to actually use the cluster config, even if it's still the same cluster.
