### ISSUE TITLE
Expand Task Param fields

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#190]
## Expected Behavior
Tasks should be reusable. When you look at a Task, it should be clear how to use it, specifically how to provide the right parameters and what they are. There should also be defaults for parameters, i.e. each Param should look like this:

```yaml
  - name: DOCKERFILE_NAME
    description: The name of the Dockerfile
    default: Dockerfile
```

* Description should be required
* Default should be optional

_Please also update examples._

## Actual Behavior
Currently Task Params have only one field: `name`.

## Additional Info
See [knative build template docs](https://github.com/knative/docs/blob/master/build/build-templates.md#example-template).

Question: perhaps we want this functionality for resources as well?
