### ISSUE TITLE
Add  `command` to `Task.BuildSpec.Steps` in all  example Task definitions.

### ISSUE THREAD

**Issue by tejal29** [knative/build-pipeline#202]
## Expected Behavior
The [`Task`](https://github.com/knative/build-pipeline/blob/master/docs/Concepts.md#task) documentation in Concepts mentions use of field `command`. 
It advises on not have an entry point set for container image.
```
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: hello-world
  namespace: default
spec:
  buildSpec:
    steps:
      - name: echo
        image: busybox
        command:
          - echo
        args:
          - "hello world!"
```
However, the [example tasks](https://github.com/knative/build-pipeline/blob/master/examples) still follow the old practice.  

## Actual Behavior
We should have examples also follow the same principles as explained in concepts documentation.

## Steps to Reproduce the Problem

  1.
  2.
  3.
