### ISSUE TITLE
Move `buildSpec` up a level inside Task.spec

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#228]
## Expected Behavior
`Task.spec` should no longer contain a `Build.spec`. All fields that we want to support from `Build` in `Task` should be moved up one level and explicitly included inside `Task.spec`, e.g.:

```yaml
spec:
      steps:
          - name: runMake
            image: ubuntu
            command: ['make']
            args: ['${inputs.params.makeTarget}']
```

## Actual Behavior
`Task.spec` contains `Build.spec`, however we limit the fields which can be used, for example we do not allow the user to provide a reference to a Build template:

https://github.com/knative/build-pipeline/blob/df83248d5bc51103288d3704cc53d7afcf852e63/pkg/apis/pipeline/v1alpha1/task_validation.go#L47-L50

Tasks currently contain a `buildSpec` field, e.g.:

```yaml
spec:
    buildSpec:
        steps:
            - name: runMake
              image: ubuntu
              command: ['make']
              args: ['${inputs.params.makeTarget}']
```

## Steps to Reproduce the Problem
n/a

## Additional Info
Part of #147
