### ISSUE TITLE
Specify Params in Pipeline

### ISSUE THREAD

**Issue by bkuschel** [knative/build-pipeline#263]
## Expected Behavior

We want to be able to provide Pipeline wide parameters which can be used in templating across Tasks.

For example, I should be able to create something like this (spec for params can be different!)

```yaml
kind: Pipeline

...
spec:
  params:
    - name: 'namespace'
      value: 'test'
      type: 'string' # this is assuming we go ahead with something like #207 and add some types
- name: deploy-bundle-test
  taskRef:
    name: deploy-with-kubectl
  inputSourceBindings:
  - name: workspace
    resourceRef:
        name: guestbook    
  params:
  - name: namespace
    value: "${params.namespace}" # this should come from the global params
```

## Actual Behavior

PipelineRun only accepts Resources, not parameters. We can specify templating within a Pipeline, but it only references Resources within the Task that uses the templating, there is no concept of global templating.

## Additional Info

For example,  have a pipeline with a helm deployment step that has a parameter that specifies the namespace to install into (for isolation.)

Strongly related to: https://github.com/knative/build-pipeline/issues/254

Note that one strange thing here is that:
* At the `Task` level, we express parameters we _want_ in `Tasks`, and we specify the params we're actually using within the `TaskRun
* At the `Pipeline` level, the params exist within the `Pipeline` only, and are never provided in the `PipelineRun`

In the future we may want to consider moving more `params` into PipelineRuns??? Maybe!

**Comment by bobcatfish** [comment]
Hey @bkuschel ! Thanks for opening this issue :D

I think we may have this functionality already, though let me know if this isn't what you're looking for.

You could have a helm task like this:

```yaml
kind: Task
metadata:
  name: deploy-with-helm
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
...
    params:
    - name: namespace
...
  steps:
  - name: deploy
    image: kubernetes-helm
    command: ['helm']
    args:
      - 'install'
      - '--namespace'
      - '${inputs.params.namespace}'
```

Then you could use templating in the Pipeline to provide the value of the namespace parameter:
```yaml
kind: Pipeline
...
- name: deploy-bundle-test
  taskRef:
    name: deploy-with-kubectl
  inputSourceBindings:
  - name: workspace
    resourceRef:
        name: guestbook    
  params:
  - name: namespace
    value: "${inputs.resources.workspace.revision}"
```
(From #64)

But you can only use inputs and outputs from the Task in the templating - I'm thinking what you want is some kind of "global" parameter (like in #254) that you can use for the namespace and pass into Tasks throughout the Pipeline?
