### ISSUE TITLE
Reduce PipelineResource bindings

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#320]
## Expected Behavior

Users should be able to effectively say something like this in a `PipelineRun`:
> “For the Pipeline, use git resource W, image resources Y + X, and deploy to cluster Z.”

## Actual Behavior

The current reality is that users have to provide theses values repeatedly, more like:

> “For Task A use git resource W and image X, for Task B use git resource W and image Y, for Task C use git resource W and image Y and image X and cluster Z…”

For example in this PipelineRun, we provide bindings for build-skaffold-web’s workspace and builtImage PipelineResources, and for deploy-web’s workspace and image PipelineResources.

```yaml
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
spec:
  pipelineRef:
    name: demo-pipeline
  triggerRef:
    type: manual
  resources:
  - name: build-skaffold
    inputs:
    - name: workspace
      resourceRef:
        name: skaffold-git
    outputs:
    - name: image1
      resourceRef:
        name: skaffold-image-leeroy-web
    - name: image2
      resourceRef:
        name: skaffold-image-leeroy-app
   - name: deploy-web
    inputs:
    - name: workspace
      resourceRef:
        name: skaffold-git
    - name: image
      resourceRef:
        name: skaffold-image-leeroy-web
```

However, when a Pipeline uses the providedBy field to link the output of one Task to the input of another, it should be possible to infer the PipelineResource to use for the Task from the providedBy field.

For example in this Pipeline, we bind the output of the build-skaffold-web Task to the input PipelineResource called image for the deploy-web Task.

```yaml
apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  tasks:
  - name: build-skaffold
    taskRef:
      name: build-push-images
  - name: deploy-web
    taskRef:
      name: demo-deploy-kubectl
    resources:
    - name: image
      providedBy:
      - build-skaffold-web
```

## Additional Info

This is related to these issues:

* https://github.com/knative/build-pipeline/issues/124 - Designing output handling
* https://github.com/knative/build-pipeline/issues/168 - Implementing DAG execution
