### ISSUE TITLE
TestPipelineRun/fan-in_and_fan-out is broken

### ISSUE THREAD

**Issue by adrcunha** [knative/build-pipeline#375]
The test is timing out after 10 minutes:

```
I0109 15:14:22.583]     --- FAIL: TestPipelineRun/fan-in_and_fan-out (600.37s)
I0109 15:14:22.583]         pipelinerun_test.go:153: Error waiting for PipelineRun helloworld-pipelinerun1 to finish: timed out waiting for the condition
```

This *seems* to occur only when running on Prow.

Sample log: 

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_build-pipeline/370/pull-knative-build-pipeline-integration-tests/1083012932113010688/

**Comment by bobcatfish** [comment]
@adrcunha can you point as at or give us some details on what the clusters look like that these tests run against?

Seems like we're going to have to tackle this by either:
1. trying to make our own clusters as similar as possible or
2. keep fiddling with this test in a PR and try to get more info about what's going on

**Comment by bobcatfish** [comment]
This looks like an ominous error log:

```
I0109 15:16:16.586] default                  28s         37s          2         pvc-3fba5047-1421-11e9-9528-42010a800053.157836feab0df1d7                         PersistentVolume                                                Normal    VolumeDelete                persistentvolume-controller                                            googleapi: Error 400: The disk resource 'projects/knative-boskos-16/zones/us-central1-b/disks/gke-kbuild-pipeline-e2-pvc-3fba5047-1421-11e9-9528-42010a800053' is already being used by 'projects/knative-boskos-16/zones/us-central1-b/instances/gke-kbuild-pipeline-e2e--default-pool-3d89c5e2-jx0x', resourceInUseByAnotherResource
```

**Comment by bobcatfish** [comment]
I think it could be interesting to figure out when this started happening. Timeline:

1. Test was added Nov 29 https://github.com/knative/build-pipeline/pull/270

Last pass:
2. Test passed on Dec 20 https://github.com/knative/build-pipeline/pull/343, in logs:
```
TestPipelineRun :PASS:
```

First failure (only doc changes b/w these 2 from what I can see, so it looks like integration tests were not run):
3. Test failed on Dec 30 https://github.com/knative/build-pipeline/pull/352, in logs:
```
I1230 15:41:23.937]     --- FAIL: TestPipelineRun/fan-in_and_fan-out (600.32s)
I1230 15:41:23.937]     	pipelinerun_test.go:153: Error waiting for PipelineRun helloworld-pipelinerun1 to finish: timed out waiting for the condition
```

**Comment by bobcatfish** [comment]
Hm I don't think that timeline is quite correct (stuff is missing), the "closed" PR order doesn't seem to be working for this, gonna try again looking at commits directly.

**Comment by bobcatfish** [comment]
Okay looking at the commits in order (https://github.com/knative/build-pipeline/commits/master) (assuming this is the right order) the first commit to fail is https://github.com/knative/build-pipeline/commit/5f28380ac16724d159b6694e76836c5076f8db4b

Logs (started at 2018-12-30 01:29 PST):
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_build-pipeline/359/pull-knative-build-pipeline-integration-tests/1079308537055678466/

The last commit to pass, right before that is:
https://github.com/knative/build-pipeline/commit/1556fafdd770efbf1791d920b9ef79228f332c3e

Logs (started at 2018-12-30 00:06 PST):
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_build-pipeline/360/pull-knative-build-pipeline-integration-tests/1079287649333678082/

(I'm not 100% sure if this includes the additional check that Tide does right before merging :thinking: )

**Comment by bobcatfish** [comment]
oooo i think i reproduced this locally by switching from region us-central-1a to zone us-central-1 (which happened in https://github.com/knative/build-pipeline/commit/5f28380ac16724d159b6694e76836c5076f8db4b via https://github.com/knative/test-infra/pull/297

The pod status:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-01-09T22:52:02Z
    message: '0/3 nodes are available: 3 node(s) had no available volume zone.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
```

The taskrun status (looks like the same error when i repro-ed in https://github.com/knative/build-pipeline/pull/377#issuecomment-452838774):
```
  status:
    conditions:
    - lastTransitionTime: 2019-01-09T22:52:14Z
      message: 'pod status "PodScheduled":"False"; message: "0/3 nodes are available:
        3 node(s) had no available volume zone."'
      reason: Pending
      status: Unknown
      type: Succeeded
    podName: helloworld-pipelinerun1-create-file-kritis-pod-d29ac6
```

How I created the cluster:
```
gcloud container clusters create --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --enable-basic-auth --no-issue-client-certificate --project=$PROJECT_ID --region=us-central1 --machine-type=n1-standard-4 --image-type=cos --num-nodes=1 --cluster-version=1.11.5 catzone
```
