### ISSUE TITLE
GCS input resources flatten files on copy

### ISSUE THREAD

**Issue by Conky5** [knative/build-pipeline#522]
## Expected Behavior

Using a GCS directory storage resource should preserve existing directory structures.

## Actual Behavior

Copies from GCS flatten files.

## Steps to Reproduce the Problem

1. Given a bucket `gs://example` which has a directory structure in it, for example:
```
gs://example/a/output.txt
gs://example/b/output.txt
```

2. Create a `PipelineResource` `storage` resource type `directory`:
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: storage-example
  namespace: default
spec:
  type: storage
  params:
    - name: type
      value: gcs
    - name: location
      value: gs://example
    - name: dir
      value: "true"
```

3. Create a task that uses the GCS bucket as an input
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example
  namespace: default
spec:
  inputs:
    resources:
      - name: storage-example
        type: storage
  steps:
    - name: example
      image: alpine
      command:
        - /bin/sh
      args:
        - -x
        - -c
        - find /workspace/storage-example -type f
        # do something  that needs to interact with directories "a" and "b", and their respective files
        # only one "output.txt" file exists and the directories "a" and "b" are not present
```

4. Task run
```
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun
  namespace: default
spec:
  taskRef:
    name: example
  inputs:
    resources:
      - name: storage-example
        resourceRef:
          name: storage-example
```

## Additional Info

The gsutil command for directories is `gsutil -r gs://bucket/** target`, if the `/**` is removed the directory structures will be preserved.

Edit: Updated examples to use new `tekton` api version names, added a `TaskRun`, and corrected the directory used in the script example
