### ISSUE TITLE
Add validation on Pipeline creation for DAG

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#559]
# Expected Behavior
In #168 we add DAG based execution for Pipelines instead of executing Tasks in the order they are declared.

The DAG is created based on the `from` and `runAfter` clauses. It is possible that these can be used to create Graphs which cannot actually execute and complete, e.g. infinite loops, etc.

If a user tries to create a `Pipeline` which contains an invalid graph, the creation should immediately fail with an informative error.

# Actual Behavior

* The logic in `pkg/reconciler/v1alpha1/pipeline/resources/dag.go` to traverse the DAG does some validation, but only at runtime.
* The [`validateFrom` function](https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/pipeline_validation.go#L70) will validate the `from` clause, but it does not assume a graph, and it doesn't validate the `runAfter` clause at all.

# Steps to Reproduce the Problem

1. Create a graph with an unresolvable loop, e.g.:
```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  tasks:
  - name: some-task-1
    taskRef:
      name: some-task
    runAfter:[ some-task-2 ]
  tasks:
  - name: some-task-2
    taskRef:
      name: some-task
    runAfter:[ some-task-1 ]
```

2. Note that there is no error at creation time
3. If you create  `PipelineRun` that tries to use this `Pipeline`, you _should_ get an error

(Note this is not the only invalid Pipeline, part of the work in this issue to find all the cases to cover)

# Additional Info

At the time of this issue creation, #473 which implements the graph is still being reviewed (not merged yet)
