### ISSUE TITLE
Pipeline uses `passedConstraints` to provide correct inputs and outputs

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#65]
## Expected Behavior
If a user creates a Pipeline which has [`passedConstraints`](https://github.com/knative/build-pipeline#resources) specified, this should be used to construct a DAG of tasks (including fan in and fan out)
2. Ensure that the version of the `Resource` used by the task is the same as the version used by the `Task`(s) in the `passedConstraint`

Should include:

* Expanding the docs about how to use `Resources` that are changed between `Tasks` and how to use `passedConstraints` to make sure the right versions are used
* Test coverage, unit and also integration if possible (see #16)

## Actual Behavior
After #61 we will have a simple `Pipeline` in which either the DAG is flat or all `Tasks` execute simultaneously; i.e. the `passedConstraints` are ignored.

## Steps to Reproduce the Problem

  1. Deploy the Pipeline CRD + related CRDs to your cluster (note: should be docs on how to do this post kubebuilder)
  3. Create a `Resource` that brings in [the hello-world docker image repo](https://github.com/docker-library/hello-world), and declares an image we will be building (`gcr.io/my-registry` must be changed to a registry that the specified serviceAccounts will have permission to push to):
```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Resource
metadata:
  name: resources
  namespace: default
spec:
  resources:
    - name: hello-world-resource
      type: github
      params:
      - name: url
        value: https://github.com/docker-library/hello-world
      - name: revision
        value: master
    - name: hello-world-image
      type: image
      params:
        - name: url
          value: gcr.io/my-registry
```
  2. Create a two Tasks, the first will build an image (using Kaniko, see #62), the second will run the image:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: build-push
  namespace: default
spec:
    inputs:
        resources:
        - name: workspace
          type: github
        params:
            - name: pathToDockerFile
              value: string
    outputs:
        resources:
        - name: imageToBuild
          type: image
    buildSpec:
      steps:
         - name: build-and-push
           image: gcr.io/kaniko-project/executor
      args:
         - --dockerfile=${DOCKERFILE}
         - --destination=${IMAGE}
```
```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: run
  namespace: default
spec:
    inputs:
        resources:
        - name: imageToRun
          type: image
    buildSpec:
      steps:
         - name: run-image
           image: "${imageToRun.url}/${imageToRun.name}"
```
  3. Create a `Pipeline` which wires the two `Tasks` together using `passedConstraints`:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
  namespace: default
spec:
    tasks:
        - name: build-hello-world
          taskRef:
              name: build-push
          inputSourceBindings:
          - key: workspace
            resourceRef:
                 name: hello-world-resource
          outputSourceBindings:
          - key: imageToBuild
             resourceRef:
                 name: hello-world-image
        - name: run-hello-world
          taskRef:
              name: run
          inputSourceBindings:
          - name: imageToRun
             resourceRef:
                 name: hello-world-image
             passedConstraints: ['build-hello-world']
```

  4. Create a `PipelineRun` which invokes the `Tasks` (you'll have to create a `PipelineParams` as well with your `serviceAccount`, in this case called `hello-world-params`:

```yaml
apiVersion: pipeline.knative.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-1
  namespace: default
spec:
    pipelineRef:
        name: hello-world-pipeline
    resourceRef:
        name: hello-world-resource
    pipelineParamsRef:
        name: hello-world-params
    triggerRef:
        type: manual
```

5. Creating the PipelineRun should have created TaskRuns with all of the values filled in, so with `kubectl get taskRuns` you should be able to see conditions updated appropriately

6. Looking at the Task logs (if this has been implemented, see #59) or at the logs for the running pod if not, you should be able to see that the hello world image was run and output [the expected value from the hello world image](https://github.com/docker-library/hello-world/blob/master/hello.c#)

7. You should be able to see `hello-world image` built and pushed to your registry.

## Additional Info
* Blocked by  #61 (simple PipelineRun) and #62 (build and push using Kaniko)
