### ISSUE TITLE
Create integration test demonstrating milestone 1

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#89]
## Expected Behavior
To make sure we work in the same direction was we work towards [our first milestone](https://github.com/knative/build-pipeline/milestone/1) we should have an integration test (which would be skipped) that attempts to perform the actions we want to demo, which we can review as a team and make sure we are happy with.

## Actual Behavior
The only description of the expected behaviour is the description of milestone 1, but we are all on slightly different pages about what we need to accomplish.

## Additional Info
https://github.com/knative/build-pipeline/milestone/1

**Comment by bobcatfish** [comment]
Started working on this but realized that most of the logic will come from @pivotal-nader-ziada 's work in #63 so I'm going to wait for that before continuing :D

**Comment by bobcatfish** [comment]
/assign @dlorenc

@dlorenc has this almost done - we also found a pile of other random things that weren't quite wired together properly that'll get fixed as part of this (including output templating from #64

**Comment by bobcatfish** [comment]
@dlorenc to send yamls he used for the demo

**Comment by bobcatfish** [comment]
@dlorenc 's yamls:

```yaml
apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
  namespace: default
spec:
    tasks:
        - name: build-skaffold-web
          taskRef:
              name: kaniko
          inputSourceBindings:
              - name: workspace
                key: workspace
                resourceRef:
                  name: workspace
          outputSourceBindings:
              - name: image
                key: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-web
          params:
              - name: pathToDockerfile
                value: Dockerfile
              - name: pathToContext
                value: /workspace/examples/microservices/leeroy-web
        - name: build-skaffold-app
          taskRef:
            name: kaniko
          inputSourceBindings:
            - name: workspace
              key: workspace
              resourceRef:
                name: workspace
          outputSourceBindings:
            - name: image
              key: builtImage
              resourceRef:
                name: skaffold-image-leeroy-app
          params:
            - name: pathToDockerfile
              value: Dockerfile
            - name: pathToContext
              value: /workspace/examples/microservices/leeroy-app
        - name: deploy
          taskRef:
            name: kubectl
          inputSourceBindings:
            - name: workspace
              key: workspace
              resourceRef:
                name: workspace
          params:
          - name: path
            value: /workspace/examples/microservices/leeroy-app/kubernetes/deployment.yaml
```
